version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
    - postgres
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.19

    depends_on:
      - postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"

    volumes:
      - ./pgadmin:/var/lib/pgadmin

    ports:
      - ${PGADMIN_PORT:-5050}:80

    networks:
      - postgres

    restart: unless-stopped

networks:
  postgres:
    driver: bridge
